### ISSUE TITLE
SSR memory leak with xstyled 3.x.x

### ISSUE THREAD

**Issue by StephaneRob** [gregberge/xstyled#371] opened 2022-06-09 12:30 UTC
## 🐛 Bug Report

We recently faced a memory leak on our SSR application after upgrading xstyled from 2.5.0 to 3.6.0.
Here are two screenshots of the memory breakdown when we released the upgrade of xstyled and the rollback.

<img width="423" alt="upgrade" src="https://user-images.githubusercontent.com/4135765/172847151-19a36c79-5ce7-46ce-8261-18c444201ce8.png">
<img width="272" alt="rollback" src="https://user-images.githubusercontent.com/4135765/172847161-222656bb-eb99-4e25-ab5c-e97a04c71588.png">

We detected a heap size continuously growing on `reduceVariants` function.

**Comment by jguddas** [comment] 2022-06-10 07:57
My guess would be that this is due to the cache continuously growing.

**Comment by gregberge** [comment] 2022-06-19 20:04
Hello @StephaneRob, thanks for pointing it out. I will dig it to understand the problem. Feel free to reach me on Twitter if you have more information.

**Comment by EmilioAiolfi** [comment] 2022-07-26 21:58
Folks some news about this?

**Comment by mleralec** [comment] 2022-08-16 13:02
Hey @gregberge, I'm trying to solve this issue, can you look at my PR https://github.com/gregberge/xstyled/pull/379 ? (it will be useful for debug 👀 )

**Comment by jguddas** [comment] 2022-08-17 18:03
I was able to reproduce this with Next.JS, the way to fix it for me here was like this:
```diff
 import { x, ThemeProvider } from '@xstyled/styled-components'

+ const theme = {}
+ 
 export default function Home() {
   return (
-    <ThemeProvider theme={{}}>
+    <ThemeProvider theme={theme}>
        <x.div color="red">Hello World</x.div>
     </ThemeProvider>
   )
 }
```

Instead of a `WeakMap` [here](https://github.com/gregberge/xstyled/blob/da38e6a4742dea8cf9e10a7ba7fcea52e61c55c1/packages/system/src/cache.ts#L16)  we could use a `Map` and on `cache.set` do something like this:

```
const MAX_CACHE_SIZE = 300
if (cache.size > MAX_CACHE_SIZE) {
  if (__DEV__) {
    console.warn('Your theme might not be getting cached properly! https://github.com/gregberge/xstyled/issues/371')
  }
  return null
}
```

This would stop caching after 300 themes and print a warning in [webpack](https://webpack.js.org/guides/package-exports/#optimizations) dev environments ([this includes next 12+](https://nextjs.org/docs/messages/webpack5)) when setup correctly with rollup and [exports.development](https://nodejs.org/api/packages.html#community-conditions-definitions) in the `package.json`.

---

We could also use something like [quick-lru](https://github.com/sindresorhus/quick-lru).

**Comment by mleralec** [comment] 2022-08-18 08:06
Hey @jguddas, thanks for your answer. What do you think of something like that ?

```diff
- const cacheSupported: boolean = typeof Map !== 'undefined' && typeof WeakMap !== 'undefined'
+ const cacheSupported: boolean = typeof Map !== 'undefined'

- const caches = cacheSupported ? new WeakMap<ITheme, ThemeCache>() : null
+ const caches = cacheSupported ? new Map<string, ThemeCache>() : null
+ const stringifyTheme = (theme: ITheme): string => JSON.stringify(theme)

const getThemeCache = (theme: ITheme): ThemeCache | null => {
   if (caches === null) return null
+  const stringifiedTheme = stringifyTheme(theme)
-  if (caches.has(theme)) return caches.get(theme) || null
+  if (caches.has(stringifiedTheme)) return caches.get(stringifiedTheme) || null
   const cache = {}
-  caches.set(theme, cache)
+  caches.set(stringifiedTheme, cache)
   return cache
}
```

If the problem is related to the `WeakMap`, we can stringify the Theme and use a classic `Map` (JSON.stringify is used here, but we can use something to hash an object like https://www.npmjs.com/package/object-hash)

**Comment by jguddas** [comment] 2022-08-18 19:02
@mleralec, this will have a significant performance impact, but we could run it in dev to throw an error like this:

```diff
+ const cacheValidation = cacheSupported ? new Map<string, true>() : null
+ 
const getThemeCache = (theme: ITheme): ThemeCache | null => {
  if (caches === null) return null
  if (caches.has(theme)) return caches.get(theme) || null
+  if (__DEV__ && cacheValidation) {
+    const stringifiedTheme = JSON.stringify(theme)
+    if (cacheValidation.has(stringifiedTheme) {
+      console.error('Your theme is not being cached properly!')
+    } else {
+      cacheValidation.set(stringifiedTheme, true)
+    }
+  }
  const cache = {}
  caches.set(theme, cache)
  return cache
}
```

**Comment by mleralec** [comment] 2022-08-18 21:05
@jguddas Thanks for your answer. 

I'm not a big fan of using variables like `__DEV__` in a library. This assumes you are using **webpack** but it won't work with **vite**, **esbuild**, **rollup**, **swc**...

I made a PR with his changes here https://github.com/gregberge/xstyled/pull/381, feel free to review it!

**Comment by theo-mesnil** [comment] 2022-10-12 12:40
Hi @gregberge ! You can close this issue, xstyled 3.7.0 fixe it :) 

Thanks @mleralec ❤️ 

![Capture d’écran 2022-10-12 à 14 39 11](https://user-images.githubusercontent.com/50322149/195344693-155d4ea2-02ac-4acb-942a-6bc8bfe8c29c.png)

**Closed** 2022-10-15 19:50 UTC
Labels: bug 🐛
