### ISSUE TITLE
tsserver performance

### ISSUE THREAD

**Issue by anilanar** [gregberge/xstyled#197] opened 2021-03-01 08:49 UTC
I want to have a place where this topic is acknowledged and planned ahead if needed.

Currently, tsserver performance is somewhat annoying due to sheer number of props in the props type, which has `number of style props * number of pseudo states` (which probably easily exceeds thousands?) props.

Perhaps using nested objects for pseudo states can be better in this regard, which actually can be implemented with a minor semver release.

**Comment by gregberge** [comment] 2021-03-12 17:23
Hello @anilanar, I am not a TypeScript expert. Every help to improve typing and make it faster is welcome!

**Comment by anilanar** [comment] 2021-03-12 17:51
@gregberge Sadly, there's nothing we can really do about this other than 

1) Ask TS to improve tsserver performance for the case where there are thousands of candidates for type completion.
2) Change the way pseudo selectors are used by using nested objects instead of using props prefixed with pseudo selector name, to reduce number of props tsserver needs to consider for type completion. 

Perhaps, just to give an idea, chakra-ui's "stystem props" don't have the same problem, possibly due to using nested objects for pseudo selectors.

**Comment by gregberge** [comment] 2021-03-15 21:58
@anilanar should we really change the API for a problem of autocompletion? I don't think so. The issue is on TSServer, not on xstyled.

**Comment by anilanar** [comment] 2021-03-15 23:25
That may sound riddiculous if you are not using Typescript and may sound essential if you are using Typescript (because it's the whole editing experience, not just mere auto-completion). So as a maintainer, depends on your priorities. 

I do agree that it should be the tsserver that fixes the problem, but from tsserver's persective, xstyled is 1 exception among thousands, if not millions, of libraries.

**Comment by gregberge** [comment] 2021-03-16 21:27
@anilanar I understand, I have to consider it for v3.

**Comment by gregberge** [comment] 2021-05-24 08:08
Fixed in v3.

**Closed by gregberge** 2021-05-24 08:08 UTC
Labels: discussion 🗣, typings 🔧
